name: Run Tests on Push

on:
  push:
    branches:
      - master  # Change to 'master' or other branch if needed
  pull_request:
    branches:
      - master  # Trigger on pull requests as well

jobs:
  test:
    runs-on: ubuntu-latest  # You can choose different runners, like macos-latest or windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # This action checks out your code

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'  # Change this to the Node.js version you want to use

    - name: Install dependencies
      run: npm install  # This will install your project dependencies

    - name: Run tests
      run: npm run test  # This will run your tests using Vitest (or other test runners you use)
